version: "3"
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  db-import:
    environment:
    - DB_HOST=db
    - DB=book
    - COLLECTION=books
    - COUNTER_COLLECTION=counters
    image: mongo
    depends_on: 
      - db
    volumes:
      - ./data:/data
    command: sh data/import.sh
  simple-books-service:
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: npm start